# Generated by Django 5.0.dev20230322100140 on 2023-04-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('namn', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('osoite', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('kaupunki', models.CharField(max_length=100)),
                ('stad', models.CharField(max_length=100)),
                ('kapasiteet', models.IntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateField()),
                ('return_time', models.DateField()),
                ('covered_distance', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('departure_station_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_station', to='apis.station')),
                ('return_station_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_station', to='apis.station')),
            ],
        ),
    ]
