# Generated by Django 5.0.dev20230322100140 on 2023-04-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_station_id_alter_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_station', to='apis.station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_station', to='apis.station'),
        ),
    ]
