# Generated by Django 5.0.dev20230322100140 on 2023-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_departure_station_id_trip_departure_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
